flask_saas/saas/app.py
from flask import Flask

from saas.blueprints.page import page


def create_app(settings_override=None):
    """
    Create a Flask app using the app factory pattern
    :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object("config.settings")
    app.config.from_pyfile("settings.py", silent=True)

    if settings_override:
        app.config.update(settings_override)

    app.register_blueprint(page)

    return app

flask_saas/saas/blueprints/page/__init__.py
from saas.blueprints.page.views import page

flask_saas/saas/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint("page", __name__, template_folder="templates")


@page.route("/")
def home():
    return render_template("page/home.html")


@page.route("/terms")
def terms():
    return render_template("page/terms.html")


@page.route("/privacy")
def privacy():
    return render_template("page/privacy.html")

flask_saas/saas/templates/layouts/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{% block meta_description %}{% endblock %}">

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <main class="container">
    <div class="md-margin-top">{% block heading %}{% endblock %}</div>
    {% block body %}{% endblock %}
  </main>

  <footer class="footer text-center">
    <div class="container">
      <ul class="list-inline">
        <li class="text-muted">SAAS</li>
        <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
        <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
      </ul>
    </div>
  </footer>
</body>

</html>